const HRMS_API_ENDPOINT = "https://script.google.com/macros/s/AKfycbyg3OPSX-y6cqOYAEqmXzDSACi-zOsQYWIy-6JJB4Epel1eAYj_n7Fzz_P2Nypa6-eW/exec";
const HRMS_STORAGE_KEY = "liumgoHrmsRecords";
const HRMS_FILE_FIELDS = ["appointmentLetter", "attendanceSheet", "kmStatement", "payslip"];

document.addEventListener("DOMContentLoaded", () => {
  const form = document.getElementById("hrms-entry-form");
  if (!form) return;
  const select = document.getElementById("hrms-record-select");
  const context = document.getElementById("hrms-record-context");
  const message = document.getElementById("hrms-message");
  const preview = document.getElementById("payroll-preview");
  let activeId = "";
  let loadingRecord = false;
  const records = () => { try { return JSON.parse(localStorage.getItem(HRMS_STORAGE_KEY) || "[]"); } catch { return []; } };
  const setUnlocked = (enabled) => { form.querySelectorAll('[data-section]:not([data-section="employee"])').forEach(section => { section.classList.toggle("entry-card--locked", !enabled); section.setAttribute("aria-disabled", String(!enabled)); section.querySelectorAll("input,select,textarea,button").forEach(control => control.disabled = !enabled); }); form.querySelectorAll("[data-open-section]").forEach(button => button.disabled = !enabled); };
  const updateStatuses = record => form.querySelectorAll("[data-section-status]").forEach(status => { const saved = Boolean(record?.sections?.[status.dataset.sectionStatus]); status.textContent = saved ? "Saved to this record" : "Not saved"; status.classList.toggle("is-saved", saved); form.querySelectorAll(`[data-short-status="${status.dataset.sectionStatus}"]`).forEach(shortStatus => { shortStatus.textContent = saved ? "Saved ✓" : "Not added"; shortStatus.classList.toggle("is-saved", saved); }); });
  const notify = (text, type) => { message.textContent = text; message.className = `entry-message entry-message--${type}`; };
  const refresh = () => { const chosen = activeId; select.innerHTML = '<option value="">New employee</option>'; records().forEach(record => { const option = document.createElement("option"); option.value = record.id; option.textContent = `${record.sections?.employee?.fullName || "Unnamed"} · ${record.sections?.employee?.employeeId || record.id}`; select.append(option); }); select.value = chosen; };
  const calculate = () => { const value = name => Number(form.elements.namedItem(name)?.value || 0); const type = form.elements.namedItem("paymentType")?.value || "Monthly"; const base = type.startsWith("Monthly") ? value("monthlySalary") : value("approvedHours") * value("hourlyRate"); const kmPay = type.includes("km") ? value("approvedKm") * value("kmRate") : 0; const gross = base + kmPay + value("incentives") + value("reimbursements"); const net = gross - value("deductions"); const money = amount => `₹${amount.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`; preview.querySelector("code").textContent = `Base ${money(base)} + KM ${money(kmPay)} + incentives ${money(value("incentives"))} + reimbursements ${money(value("reimbursements"))} − deductions ${money(value("deductions"))} = net ${money(net)}`; return { basePay: base, kmPayment: kmPay, grossPay: gross, netPay: net }; };
  form.addEventListener("input", calculate); form.addEventListener("submit", event => event.preventDefault());
  form.addEventListener("click", event => { const opener = event.target.closest("[data-open-section]"); if (!opener) return; form.querySelector(`[data-section="${opener.dataset.openSection}"]`)?.scrollIntoView({ behavior: "smooth", block: "start" }); });
  form.addEventListener("click", async event => { const button = event.target.closest("[data-save-section]"); if (!button) return; const name = button.dataset.saveSection; if (name !== "employee" && !activeId) return notify("Save or select an employee first.", "error"); const section = form.querySelector(`[data-section="${name}"]`); const invalid = [...section.querySelectorAll("input,select,textarea")].find(control => !control.checkValidity()); if (invalid) { invalid.reportValidity(); return notify("Complete the required fields before saving.", "error"); } const files = [...section.querySelectorAll('input[type="file"]')].flatMap(input => input.files[0] ? [{ field: input.name, file: input.files[0] }] : []); const oversized = files.find(item => item.file.size > 10 * 1024 * 1024); if (oversized) return notify(`${oversized.file.name} is larger than 10 MB.`, "error"); const fields = Object.fromEntries([...section.querySelectorAll("input:not([type=file]),select,textarea")].map(control => [control.name, control.value])); if (name === "payroll") Object.assign(fields, calculate()); if (!activeId) activeId = `HR-${Date.now().toString(36).toUpperCase()}`; const all = records(); let record = all.find(item => item.id === activeId); if (!record) { record = { id: activeId, sections: {}, createdAt: new Date().toISOString() }; all.push(record); } record.sections[name] = { ...fields, documentNames: files.map(item => item.file.name), savedAt: new Date().toISOString() }; record.updatedAt = new Date().toISOString(); localStorage.setItem(HRMS_STORAGE_KEY, JSON.stringify(all)); setUnlocked(true); refresh(); context.textContent = `Adding information for ${record.sections.employee?.fullName || activeId}.`;
    updateStatuses(record);
    if (!HRMS_API_ENDPOINT) return notify(`${name} saved locally for prototype use. Configure HRMS_API_ENDPOINT for Drive storage.`, "success");
    button.disabled = true; notify(`Uploading ${name}…`, "working"); try { const documents = await Promise.all(files.map(async item => ({ field: item.field, name: item.file.name, type: item.file.type, data: await toBase64(item.file) }))); const response = await fetch(HRMS_API_ENDPOINT, { method:"POST", headers:{"Content-Type":"text/plain;charset=utf-8"}, body:JSON.stringify({ recordId:activeId, section:name, fields, documents }) }); const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error || "Storage rejected the update."); notify(`${name} saved to Google Drive and the HRMS register.`, "success"); } catch (error) { notify(`Drive upload failed: ${error.message}. A local prototype copy remains saved.`, "error"); } finally { button.disabled = false; }
  });
  select.addEventListener("change", () => { if (!select.value) { form.reset(); return; } const record=records().find(item=>item.id===select.value); if (!record) return; loadingRecord=true; form.reset(); loadingRecord=false; activeId=record.id; Object.values(record.sections || {}).forEach(section=>Object.entries(section).forEach(([key,value])=>{ const control=form.elements.namedItem(key); if(control && control.type!=="file" && ["string","number"].includes(typeof value)) control.value=value; })); setUnlocked(true); updateStatuses(record); calculate(); context.textContent=`Adding information for ${record.sections.employee?.fullName || activeId}.`; });
  form.addEventListener("reset", () => { if (loadingRecord) return; setTimeout(() => { activeId=""; select.value=""; setUnlocked(false); updateStatuses(); context.textContent="Save an employee first, or select a locally saved record."; message.className="entry-message"; }, 0); });
  refresh(); setUnlocked(false); updateStatuses();
});
function toBase64(file) { return new Promise((resolve, reject) => { const reader=new FileReader(); reader.onload=()=>resolve(String(reader.result).split(",")[1]); reader.onerror=reject; reader.readAsDataURL(file); }); }
